"""
unitMail Common Library

This module provides shared components for the unitMail application including:
- SQLite-based email storage
- Pydantic models for data validation
- Configuration management
- Custom exceptions
"""

from .config import (
    APISettings,
    CryptoSettings,
    DNSSettings,
    LoggingSettings,
    MeshSettings,
    Settings,
    SMTPSettings,
    get_settings,
    reload_settings,
)
from .exceptions import (
    AuthenticationError,
    ConfigurationError,
    ConnectionError,
    CryptoError,
    DatabaseError,
    DecryptionError,
    DNSError,
    DNSLookupError,
    DuplicateRecordError,
    EncryptionError,
    InvalidConfigError,
    InvalidCredentialsError,
    InvalidMessageError,
    MessageDeliveryError,
    MessageError,
    MessageQueueError,
    MeshError,
    MissingConfigError,
    PeerConnectionError,
    PeerNotFoundError,
    PermissionDeniedError,
    QueryError,
    RecordNotFoundError,
    SignatureError,
    SMTPAuthError,
    SMTPConnectionError,
    SMTPError,
    TokenExpiredError,
    TokenInvalidError,
    TransactionError,
    UnitMailError,
    ValidationError,
)
from .models import (
    BaseDBModel,
    Config,
    Contact,
    ContactCreate,
    ContactUpdate,
    Folder,
    FolderCreate,
    FolderType,
    FolderUpdate,
    MeshPeer,
    MeshPeerStatus,
    Message,
    MessageCreate,
    MessagePriority,
    MessageStatus,
    MessageUpdate,
    QueueItem,
    QueueItemStatus,
    User,
)
from .storage import (
    EmailStorage,
    get_storage,
)
from .local_storage import (
    LocalEmailStorage,
    get_local_storage,
)

__all__ = [
    # Storage
    "EmailStorage",
    "LocalEmailStorage",
    "get_storage",
    "get_local_storage",
    # Models
    "BaseDBModel",
    "User",
    "Message",
    "MessageCreate",
    "MessageUpdate",
    "MessageStatus",
    "MessagePriority",
    "Contact",
    "ContactCreate",
    "ContactUpdate",
    "QueueItem",
    "QueueItemStatus",
    "Config",
    "MeshPeer",
    "MeshPeerStatus",
    "Folder",
    "FolderCreate",
    "FolderUpdate",
    "FolderType",
    # Configuration
    "Settings",
    "SMTPSettings",
    "APISettings",
    "DNSSettings",
    "MeshSettings",
    "CryptoSettings",
    "LoggingSettings",
    "get_settings",
    "reload_settings",
    # Exceptions
    "UnitMailError",
    "DatabaseError",
    "ConnectionError",
    "QueryError",
    "RecordNotFoundError",
    "DuplicateRecordError",
    "TransactionError",
    "AuthenticationError",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "TokenInvalidError",
    "PermissionDeniedError",
    "ConfigurationError",
    "MissingConfigError",
    "InvalidConfigError",
    "MessageError",
    "InvalidMessageError",
    "MessageDeliveryError",
    "MessageQueueError",
    "SMTPError",
    "SMTPConnectionError",
    "SMTPAuthError",
    "DNSError",
    "DNSLookupError",
    "MeshError",
    "PeerConnectionError",
    "PeerNotFoundError",
    "CryptoError",
    "EncryptionError",
    "DecryptionError",
    "SignatureError",
    "ValidationError",
]
